### ISSUE TITLE
Can you check that all the STL's are up to date? 

### ISSUE THREAD

**Issue by madhephaestus** [WPIRoboticsEngineering/ZenRobotBuildKit#6]
Check what they look like in GitHub to see if it's right. 

It would also be convenient if you moved all STL's into their own folder at this point (and moving forward)

**Comment by nickbertozzi** [comment]
Hi Kevin,

I’m on another call till 9 AM and then will look at this.

Thanks,

Nick

**Comment by nickbertozzi** [comment]
An STL folder has been created.  Old STLs were deleted, new ones were generated and added to the new STL folder.

**Comment by nickbertozzi** [comment]
Note that we need two bushings per set.
