### ISSUE TITLE
Modifications to ServoBracket

### ISSUE THREAD

**Issue by nickbertozzi** [WPIRoboticsEngineering/ZenRobotBuildKit#7]
Working on ServoBracket modifications to fit new servo.

**Comment by madhephaestus** [comment]
Should i call a production hold to the older design then?

**Comment by madhephaestus** [comment]
Production is held pending resolution of this ticket.

**Comment by madhephaestus** [comment]
Commit the updated stl with this issue in the commit and close the issue to hand off the stl to me

**Comment by nickbertozzi** [comment]
Modifications to ServoBracket completed.
